apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-exporter
  namespace: monitoring
  labels:
    app: strava-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava-exporter
  template:
    metadata:
      labels:
        app: strava-exporter
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: copy-strava-secret
          image: busybox:1.36
          command: ["sh", "-c", "cp /tmp/strava_tokens.json /app/data/strava_tokens.json"]
          volumeMounts:
            - name: strava-tokens-secret
              mountPath: /tmp/strava_tokens.json
              subPath: strava_tokens.json
            - name: strava-data
              mountPath: /app/data
      containers:
        - name: strava-exporter
          image: ghcr.io/bomaseko/strava-exporter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9400
              name: metrics
          volumeMounts:
            - name: strava-data
              mountPath: /app/data
      volumes:
        - name: strava-tokens-secret
          secret:
            secretName: strava-tokens
        - name: strava-data
          emptyDir: {}

