apiVersion: v1
kind: Service
metadata:
  name: strava-exporter
  namespace: monitoring
spec:
  selector:
    app: strava-exporter
  ports:
    - protocol: TCP
      port: 9400
      targetPort: 9400
      name: metrics

