apiVersion: v1
kind: Secret
metadata:
  name: strava-secrets
  namespace: monitoring
type: Opaque
stringData:
  STRAVA_CLIENT_ID: "201127"
  STRAVA_CLIENT_SECRET: "81845bccc04242e84c70250b4a1de01587c8c092"
  STRAVA_REFRESH_TOKEN: "09404077d0b839b854c9c707616cb1d5d51310dc"

