apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-nodeport
  namespace: selenium
spec:
  type: NodePort
  selector:
    app: selenium-hub
  ports:
    - port: 4444
      targetPort: 4444
      nodePort: 30444

