apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-pvc
  namespace: grocy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: grocy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
      - name: grocy
        image: linuxserver/grocy:latest
        ports:
        - containerPort: 9283
        volumeMounts:
        - name: grocy-data
          mountPath: /config
      volumes:
      - name: grocy-data
        persistentVolumeClaim:
          claimName: grocy-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grocy
  namespace: grocy
spec:
  type: ClusterIP
  selector:
    app: grocy
  ports:
    - port: 9283
      targetPort: 80

