apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 1000

      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /config /cache /media || true
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-cache
              mountPath: /cache
            - name: jellyfin-media
              mountPath: /media

      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          env:
            - name: JELLYFIN_PUBLISHED_SERVER_URL
              value: "https://jellyfin.maseko-lab.xyz"
            - name: JELLYFIN_BASEURL
              value: "/"
          ports:
            - containerPort: 8096
          readinessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: jellyfin-media
              mountPath: /media
              readOnly: true
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-cache
              mountPath: /cache
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"

      volumes:
        - name: jellyfin-media
          hostPath:
            path: /mnt/media
            type: Directory
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: jellyfin-cache-pvc

