apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  namespace: jellyfin
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  namespace: jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/jellyfin/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache-pv
  namespace: jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/jellyfin/cache
