apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 88def58d-6070-4e49-ab4b-9d57f88d912c
    credentials-file: /etc/cloudflared/credentials/credentials.json

    ingress:
      - hostname: mealie.maseko-lab.xyz
        service: http://10.104.175.99:9000
        originRequest:
          noTLSVerify: true

      - service: http_status:404   # catch-all for anything else

