apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongo-express
spec:
  selector:
    app: mongodb-pod
  ports:
    - name: mongodb-svc
      protocol: TCP
      port: 27017
      targetPort: 27017

